import Head from "next/head";
import Image from "next/image";

import { Headers, ProductSwap } from "../components";
export default function Home() {
  return (
    <div class="dark ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-screen dark:bg-gray-900">
        <Headers />
        <div className="flex p-20 items-center  justify-center">
          <ProductSwap />
        </div>
      </div>
    </div>
  );
}
